### PR TITLE
Sa/sc 22940/update tiledb2.12

### PR DESCRIPTION
**Pull request by anastasop**
This updates TileDB to 2.12.0

First question: Is this necessary or we can live with 2.11.3?

Second, I want comments on the build procedure i used, i am not a py expert.

I changed setup.py, added 2.12.0 and `pip install .` Then `pip freeze >requirements.txt` and there are many updates to packages.

Should i have edited `requirements.txt` and used `pip -r` to reduce updates of other packages?

### CODE REVIEW

**Review by Shelnutt2 — CHANGES_REQUESTED** [review]
I don't believe we should upgrade the pin. This is just a minimum, and there are no additional features we need from 0.18.0 here.

**Comment by thetorpedodog** [comment]
`requirements.txt` just lists the exact versions of all the packages that were used when installing the package in a particular instance. It is not actually used in production. It represents *a* known-good installation (not necessarily *the* known-good installation).

This change probably doesn’t need to happen at all; as Seth notes, the version we ask for in `setup.py` is just a minimum and this package does not *use* any features from the new version, so when it is installed in an environment that has a newer `tiledb` installed, it will work fine.

**Comment by anastasop** [comment]
Removed the commit for `requirements.txt`

JupyterHub builds with `pip install` without `-r` as Paul mentioned.

@thetorpedodog when does it make sense to pin dependencies? Only when newer versions cause problems?

**Comment by anastasop** [comment]
@Shelnutt2 @thetorpedodog Are there any other changes needed for approval?

**Comment by thetorpedodog** [comment]
Like I said, I do not think this change needs to be made at all. This does not use any new features from 0.18.0 so there is no need to update the dependencies.

**Comment by anastasop** [comment]
Closing. We go on with 0.0.35 the last tested release

**Pull request closed without merging**
